// Regenerates src/lib/demoData.ts: synthetic incidents for demo mode, with H3 outlines computed
// here so the app does not need the H3 library.  Run: node scripts/gen-demo.mts
import { writeFileSync } from "node:fs";
import { publicLabel, requireCategory } from "@warden/shared";
import { cellBoundary, cellCenter, cellsFor, publicCellFor } from "@warden/shared/geo";

const ITEMS = [
  ["Ikeja", 6.6018, 3.3515, "phone_snatching", 40, 1, "unconfirmed"],
  ["Yaba", 6.5095, 3.3711, "theft", 150, 1, "unconfirmed"],
  ["Ojuelegba", 6.51, 3.364, "one_chance", 95, 2, "unconfirmed"],
  ["Oshodi", 6.555, 3.3439, "road_blockage", 25, 1, "unconfirmed"],
  ["Lekki", 6.4474, 3.472, "flood", 210, 3, "verified"],
  ["Surulere", 6.4969, 3.3481, "crash", 70, 1, "unconfirmed"],
  ["Mile 2", 6.4655, 3.317, "armed_robbery", 290, 2, "verified"],
  ["Ikorodu", 6.6194, 3.5105, "fake_checkpoint", 120, 2, "unconfirmed"],
  ["Victoria Island", 6.4281, 3.4219, "protest", 45, 1, "unconfirmed"],
  ["Apapa", 6.449, 3.359, "theft", 1300, 1, "resolved"],
  ["Garki", 9.031, 7.488, "theft", 110, 1, "unconfirmed"],
  ["Wuse", 9.0765, 7.479, "suspicious_behaviour", 60, 1, "unconfirmed"],
  ["Nyanya", 9.017, 7.565, "armed_robbery", 350, 3, "verified"],
  ["Kubwa", 9.15, 7.34, "fire", 170, 2, "unconfirmed"],
  ["Lugbe", 8.98, 7.38, "kidnapping", 470, 2, "verified"],
  ["Gwarinpa", 9.11, 7.4, "crash", 15, 1, "unconfirmed"],
] as const;

const incidents = ITEMS.map(([place, lat, lng, categoryId, minutesAgo, reports, state], i) => {
  const category = requireCategory(categoryId);
  const cell = publicCellFor(cellsFor(lat, lng), category.severity);
  const round = (n: number) => Math.round(n * 1e6) / 1e6;
  return {
    id: `demo-${i + 1}`,
    place,
    categoryId,
    severity: category.severity,
    label: publicLabel(state, reports),
    reportCount: reports,
    minutesAgo,
    active: state !== "resolved",
    cell,
    center: cellCenter(cell),
    boundary: cellBoundary(cell).map(([x, y]) => [round(x), round(y)]),
  };
});

const out = `// Generated by scripts/gen-demo.mts. Synthetic data for demo mode only. Do not edit.
import type { CategoryId, PublicLabel, Severity } from "@warden/shared";

export interface DemoIncident {
  id: string;
  place: string;
  categoryId: CategoryId;
  severity: Severity;
  label: PublicLabel;
  reportCount: number;
  minutesAgo: number;
  active: boolean;
  cell: string;
  center: { lat: number; lng: number };
  boundary: [number, number][];
}

export const DEMO_INCIDENTS: DemoIncident[] = ${JSON.stringify(incidents, null, 2)};
`;
writeFileSync(new URL("../src/lib/demoData.ts", import.meta.url), out);
console.log(`Wrote ${incidents.length} demo incidents`);
